language: cpp
compiler: gcc
before_install: 
        - sudo apt-get update -qq
        - sudo apt-get install perl "x11proto-*" libssl-dev "libx11-*" \
                "libfontconfig*" libfreetype6-dev libx11-dev libxcursor-dev \
                libxft-dev libxi-dev libxrandr-dev libxrender-dev \
                "libdbus-*" libgtk2.0-dev libglib2.0-dev 
script: ./ci-build.sh
