language: cpp
compiler: gcc
before_install: 
        - sudo apt-get update -qq
        - sudo apt-get install -qq perl libssl-dev pv
        - sudo apt-get install -qq xorg "x11proto-*" "libx11-*" "libglib*" "libgtk*"
        - sudo apt-get install -qq libfontconfig1-dev libfreetype6-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxrandr-dev libxrender-dev
        - sudo apt-get install -qq libqt4-dev qt4-dev-tools
script: sh -x ./ci-build.sh
after_failure:
        - uname -a
        - ls -l
        - tail -n 100 build.log
